### ISSUE TITLE
tagsTooltipMode breaks when nbtTooltipMode is disabled

### ISSUE THREAD

**Issue by WenXin20** [SnowShock35/jei-integration#8]
`Minecraft v1.16.4`
`Forge v35.1.13`
`JEI Integration v6.1.1.11`

The config doesn't seem to work. By default, it shows everything is disabled, by when in-game, I still see all the tooltips. And changing the tags to display 'onShift' doesn't work either.

**Comment by WenXin20** [comment]
It also seems like tags will only show if nbt tooltip is also enabled.

**Comment by GeekJokes** [comment]
Not really the same problem but i guess it's similar: the setting for tags doesnt really give me any tags, just "ID:minecraft:iron_ingot" for example, instead of the forge:ingot and such

**Comment by JamesTheAwesomeDude** [comment]
It's working fine for me on

- Minecraft `1.16.4`
- Forge `35.1.4` (MCP `20201102.104115`)
- JEI `7.6.1.65`
- JEI Integration `6.1.1.11`
![2021-01-14_14 03 08](https://user-images.githubusercontent.com/2776014/104649138-76d69680-5671-11eb-933a-85569bee8c24.png)
![2021-01-14_14 03 12](https://user-images.githubusercontent.com/2776014/104649142-7807c380-5671-11eb-8c86-e9172c48936f.png)

**Comment by JamesTheAwesomeDude** [comment]
To enable this, you have to go into `.minecraft/config/jeiintegration-client.toml` and set

```toml
[tooltip_options]

	# Configure tooltip for NBT data.
	nbtTooltipMode = "enabled"
```

**Comment by WenXin20** [comment]
What I mean is that I want to disable nbt and enable tags only, but tags do not show unless nbt is enabled.

**Comment by JamesTheAwesomeDude** [comment]
I don't *think* I can confirm this bug, then.

```toml
[tooltip_options]
	# Configure tooltip for burn time.
	burnTimeTooltipMode = "disabled"
	# Configure tooltip for registry name. E.g. minecraft:stone
	registryNameTooltipMode = "disabled"

	# Configure tooltip for NBT data.
	nbtTooltipMode = "disabled"

	# Configure tooltip for translation key. E.g. block.minecraft.stone
	translationKeyTooltipMode = "disabled"
	# Configure tooltip for max stack size.
	maxStackSizeTooltipMode = "disabled"

	# Configure tooltip for tags. E.g. forge:ingot, minecraft:planks
	tagsTooltipMode = "enabled"

	# Configure tooltip for durability.
	durabilityTooltipMode = "disabled"
	# Configure tooltip for hunger and saturation.
	foodTooltipMode = "disabled"
```

![2021-01-14_14 45 38](https://user-images.githubusercontent.com/2776014/104653072-48f45080-5677-11eb-8f82-ca365f316691.png)
![2021-01-14_14 45 40](https://user-images.githubusercontent.com/2776014/104653075-4a257d80-5677-11eb-95de-a19205d1f3f1.png)
